server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: system
    driver-class-name: com.mysql.jdbc.Driver
 
  application:
    name: HOTEL-SERVICE    #if I don’t put application name then in eureka server console applicationName will be presented as UNKWON, we can see in above screenshot of eureka page
 
  jpa:
    hibernate:
      ddl-auto: update
#    generate-ddl: true
    show-sql: true
    
#  eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#      
#  instance:
#    prefer-ip-address: true 